NDEBUG    := 
MPI       := 
OMP       :=
PROF      :=
COMP      := gfortran
TILING    :=

HYPRE  := 

# define the location of the VARDEN root directory
VARDEN_TOP_DIR := ../..

#define the locatino of the BoxLib root directory
BOXLIB_HOME := $(HOME)/BoxLib

# include the MAESTRO build stuff
include $(VARDEN_TOP_DIR)/GVarden.mak
